version: '3.1'

services:
  postgres-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      APP_DB_USER: postgres
      APP_DB_PASS: password
      APP_DB_NAME: postgres
    #    volumes:
    #      - ./postgresql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
    #      - ./postgresql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    #      - ./postgresql:/docker-entrypoint-initdb.d/
    ports:
      - ${POSTGRES_PORT:-5432}:5432
